
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml


# kustomize build kustomize/ |kubectl apply -f -