version: '3'
networks:
  goadmin:
    driver: bridge
services:
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/kuzane/mysql:8.4.2
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: goadmin
    volumes:
      - ./data:/var/lib/mysql
      - ./base.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - goadmin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  goadmin:
    image: registry.cn-hangzhou.aliyuncs.com/kuzane/goadmin:latest
    container_name: goadmin
    hostname: goadmin
    restart: always
    ports:
      - '8000:8000'
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8000
      SERVER_HOST: http://localhost:8000
      DATABASE_DRIVER: mysql
      DATABASE_DATASOURCE: root:123456@tcp(mysql:3306)/goadmin?parseTime=true
      LOAD_WEB: true
      LOG_LEVEL: debug
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - goadmin