name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        logout: true
    
    - name: build image
      run: |
        make image
        docker tag goadmin:latest ${{ secrets.USERNAME }}/flask-demo:${{ github.sha }}
        docker push ${{ secrets.USERNAME }}/goadmin:${{ github.sha }}
